version: '3'
services:
  scanner:
    build: ./bt-sensor
    privileged: true
    network_mode: "host"
    environment:
      ID: "02"
      DEV_ID: "hci0"
      MACS: "01:01:01:01:01:00"
  broadcaster:
    build: ./bt-sensor
    privileged: true
    network_mode: "host"
    environment:
      ID: "12"
      DEV_ID: "hci1"
      MACS: ""
  mosquitto:
    image: eclipse-mosquitto
    hostname: "mosquitto"
    expose:
      - "1883"
    ports:
      - "1883:1883"
  bridge:
    build: ./communication
    depends_on:
      - mosquitto
    privileged: true
    network_mode: "host"
    environment:
      ID: "2"
      HOST: "bathduck"
      PUB: "0"
  control:
    build: ./control
    privileged: true
    network_mode: "host"
    environment:
      ID: "2"
      IDS: "0 1"
      GOOSE: "true"
  motors:
    image: duckietown/rpi-duckiebot-joystick-demo:master18
    privileged: true
    network_mode: "host"
    volumes:
      - duckietown-data:/data

volumes:
  duckietown-data:
