version: '3'
services:
  scanner:
    build: ./bt-sensor
    privileged: true
    network_mode: "host"
    environment:
      ID: "02"
      DEV_ID: "hci0"
      MACS: "01:01:01:01:01:00"
  broadcaster:
    build: ./bt-sensor
    privileged: true
    network_mode: "host"
    environment:
      ID: "12"
      DEV_ID: "hci1"
      MACS: ""
  mosquitto:
    image: eclipse-mosquitto
    hostname: "mosquitto"
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
  bridge:
    build: ./communication
    depends_on:
      - mosquitto
    privileged: true
    network_mode: "host"
    environment:
      ID: "2"
      HOST: "bathduck"
      PUB: "0"
    
