version: '3'
services:
  scanner:
    build: ./bt-sensor
    privileged: true
    network_mode: "host"
    environment:
      ID: "01"
      DEV_ID: "hci0"
      MACS: "01:01:01:01:01:00 01:01:01:01:01:12"
  bridge:
    build: ./communication
    privileged: true
    network_mode: "host"
    environment:
      ID: "1"
      HOST: "192.168.1.70"
      PUB: "0 2"
