version: '3'
services:
  broadcaster:
    build: ./bt-sensor
    privileged: true
    network_mode: "host"
    environment:
      ID: "00"
      DEV_ID: "hci0"
      MACS: ""
  bridge:
    build: ./communication
    privileged: true
    network_mode: "host"
    environment:
      ID: "0"
      HOST: "192.168.1.70"
      PUB: ""
